# Data Loading
select count(*) from customers;
select count(*) from orders;
select count(*) from products;
select count(*) from sellers;

# Data Cleaning

SET SQL_SAFE_UPDATES = 0;

UPDATE orders 
SET 
    order_purchase_timestamp = IF(order_purchase_timestamp = '', NULL, STR_TO_DATE(order_purchase_timestamp, '%Y-%m-%d %H:%i:%s')),
    order_approved_at = IF(order_approved_at = '', NULL, STR_TO_DATE(order_approved_at, '%Y-%m-%d %H:%i:%s')),
    order_delivered_carrier_date = IF(order_delivered_carrier_date = '', NULL, STR_TO_DATE(order_delivered_carrier_date, '%Y-%m-%d %H:%i:%s')),
    order_delivered_customer_date = IF(order_delivered_customer_date = '', NULL, STR_TO_DATE(order_delivered_customer_date, '%Y-%m-%d %H:%i:%s')),
    order_estimated_delivery_date = IF(order_estimated_delivery_date = '', NULL, STR_TO_DATE(order_estimated_delivery_date, '%Y-%m-%d %H:%i:%s'));

ALTER TABLE orders 
MODIFY COLUMN order_purchase_timestamp DATETIME,
MODIFY COLUMN order_approved_at DATETIME,
MODIFY COLUMN order_delivered_carrier_date DATETIME,
MODIFY COLUMN order_delivered_customer_date DATETIME,
MODIFY COLUMN order_estimated_delivery_date DATETIME;

-- For order_items
UPDATE order_items SET price = NULL WHERE price = '';
UPDATE order_items SET freight_value = NULL WHERE freight_value = '';
ALTER TABLE order_items MODIFY COLUMN price FLOAT, MODIFY COLUMN freight_value FLOAT;

-- For payments
UPDATE payments SET payment_value = NULL WHERE payment_value = '';
UPDATE payments SET payment_installments = NULL WHERE payment_installments = '';
ALTER TABLE payments MODIFY COLUMN payment_value FLOAT, MODIFY COLUMN payment_installments INT;

# Changing column name
ALTER TABLE products 
RENAME COLUMN `ï»¿product_id` TO product_id;

ALTER TABLE customers 
RENAME COLUMN `ï»¿customer_id` TO customer_id;

ALTER TABLE order_items 
RENAME COLUMN `ï»¿order_id` TO order_id;

ALTER TABLE orders 
RENAME COLUMN `ï»¿order_id` TO order_id;

ALTER TABLE payments 
RENAME COLUMN `ï»¿order_id` TO order_id;

ALTER TABLE sellers 
RENAME COLUMN `ï»¿seller_id` TO seller_id;

# Functions are not case sensitive
DESCRIBE orders;
describe products;
Describe sellers;
DesCriBE customers;
describe order_items;
describe payments;


# BASIC PROBLEM
-- 1. List all unique cities where customers are located.
select distinct(customer_city) from customers;

-- 2. Count the number of orders placed in 2017.
# select count(*) from orders where year(order_purchase_timestamp) = 2017;
select count(*) as orders_2017 from orders where year(order_purchase_timestamp) = 2017;

-- 3. Find the total sales per category. 
select p.`product category`, sum(oi.price) as total_sales from products p join order_items oi on p.product_id=oi.product_id group by p.`product category` order by total_sales desc;

-- 4. Calculate the percentage of orders that were paid in installments. 
SELECT 
    (COUNT(DISTINCT CASE WHEN payment_installments > 1 THEN order_id END) * 100.0) / 
    COUNT(DISTINCT order_id) AS installment_percentage 
FROM payments;

-- 5. Count the number of customers from each state.
select customer_state, count(*) as number_of_customers from customers group by customer_state;

# Intermediate Problems:
-- 1. Calculate the number of orders per month in 2018.
select monthname(order_purchase_timestamp) as month_name, count(*) as order_count from orders where year(order_purchase_timestamp)=2018 group by month_name, month(order_purchase_timestamp) order by month(order_purchase_timestamp);

-- 2. Find the average number of products per order, grouped by customer city. 
select customer_city, avg(items_per_order) as average_products
from (select c.customer_city, o.order_id, count(oi.product_id) as items_per_order
from customers c
join orders o on c.customer_id = o.customer_id
join order_items oi on o.order_id = oi.order_id
group by c.customer_city, o.order_id)
as order_counts group by customer_city order by average_products desc;

-- 3. Calculate the percentage of total revenue contributed by each product category. 
select p.`product category` as product_category, sum(oi.price) as category_revenue, (sum(price) / (select sum(price) from order_items)) * 100 as revenue_percentage
from products p
join order_items oi on p.product_id = oi.product_id
group by product_category
order by revenue_percentage desc;

-- 4. Identify the correlation between product price and the number of times a product has been purchased.
SELECT product_id, AVG(price) AS avg_price, COUNT(*) AS purchase_count
FROM order_items
GROUP BY product_id
ORDER BY purchase_count DESC;

-- 5. Calculate the total revenue generated by each seller, and rank them by revenue.
select seller_id, sum(price) as total_revenue, rank() over (order by sum(price) desc) as seller_rank
from order_items
group by seller_id
order by seller_rank;

# Advanced Problems:
-- 1. Calculate the moving average of order values for each customer over their order history. 
WITH OrderTotals AS (SELECT c.customer_unique_id, o.order_purchase_timestamp, SUM(p.payment_value) as total_order_value
    FROM customers c
    JOIN orders o ON c.customer_id = o.customer_id
    JOIN payments p ON o.order_id = p.order_id
    GROUP BY c.customer_unique_id, o.order_id, o.order_purchase_timestamp)
SELECT customer_unique_id, order_purchase_timestamp, total_order_value, AVG(total_order_value) OVER (
        PARTITION BY customer_unique_id ORDER BY order_purchase_timestamp ROWS BETWEEN 1 PRECEDING AND CURRENT ROW
    ) AS moving_avg_2_orders FROM OrderTotals;

-- 2. Calculate the cumulative sales per month for each year.
with monthly_sales as (
    select year(order_purchase_timestamp) as year, month(order_purchase_timestamp) as month, sum(p.payment_value) as sales
    from orders o join payments p on o.order_id = p.order_id group by year, month)
select year, month, sales, SUM(sales) over (partition by year order by month) as cumulative_sales
from monthly_sales;

-- 3. Calculate the year-over-year growth rate of total sales.
with yearly_sales as (
    select year(o.order_purchase_timestamp) as year, sum(p.payment_value) as total_revenue
    from orders o join payments p on o.order_id = p.order_id group by year)
select year, total_revenue, lag(total_revenue) over (order by year) as prev_year_revenue,
    ((total_revenue - lag(total_revenue) over (order by year)) / lag(total_revenue) over (order by year)) * 100 as yoy_growth_percentage
from yearly_sales;

-- 4. Calculate the retention rate of customers, defined as the percentage of customers who make another purchase within 6 months of their first purchase. 
WITH first_purchase AS (
    SELECT customer_id, MIN(order_purchase_timestamp) AS first_purchase_date
    FROM orders
    GROUP BY customer_id),
repeat_purchase AS (
    SELECT o.customer_id, 1 AS is_retained FROM orders o JOIN first_purchase f ON o.customer_id = f.customer_id
    WHERE o.order_purchase_timestamp > f.first_purchase_date AND o.order_purchase_timestamp <= DATE_ADD(f.first_purchase_date, INTERVAL 6 MONTH)
    GROUP BY o.customer_id)
SELECT ROUND(COUNT(DISTINCT r.customer_id) / COUNT(DISTINCT f.customer_id), 4) AS retention_rate
FROM first_purchase f LEFT JOIN repeat_purchase r ON f.customer_id = r.customer_id;

-- 5. Identify the top 3 customers who spent the most money in each year.
WITH customer_spending AS (
    SELECT year(o.order_purchase_timestamp) as year, c.customer_unique_id, sum(p.payment_value) as total_spent
    from customers c
    join orders o on c.customer_id = o.customer_id
    join payments p on o.order_id = p.order_id
    group by year, c.customer_unique_id
), ranked_customers as (
    select year, customer_unique_id, total_spent, dense_rank() over (partition by year order by total_spent desc) as spend_rank
    from customer_spending)
select * from ranked_customers where spend_rank <= 3;
